TrainingArguments:
  solver: "liblinear"  # Solver for Logistic Regression
  penalty: "l2"  # Regularisation type
  random_state: 42  # Random state for reproducibility
  max_iter: 200  # Maximum iterations for convergence
  class_weight: "balanced"  # Handle class imbalance automatically
  max_features: 10000  # Maximum number of features for TF-IDF
  ngram_range: [1, 2]  # Use unigrams and bigrams
  stop_words: "english"  # Remove English stopwords
  min_df: 2  # Minimum document frequency for a term
  max_df: 0.9  # Maximum document frequency for a term