artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/priya-roy/unhealthy-comments-Dataset/raw/refs/heads/main/commentClassification.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

# Data Transformation Configuration
data_transformation:
  text_column: "comment"  # Column containing the text comments
  label_column: "healthy"  # Column containing the labels (0: Toxic, 1: Healthy)
  stopwords: "english"  # Language for stopword removal
  lowercase: true  # Convert text to lowercase
  remove_special_characters: true  # Remove special characters from text
  remove_extra_spaces: true  # Remove extra spaces
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/commentClassification
  tokenizer_name: "nltk"  # Tokenisation library to use

# TF-IDF Vectorisation Configuration
tfidf_vectorizer:
  max_features: 10000  # Maximum number of features for TF-IDF
  ngram_range: [1, 2]  # Use unigrams and bigrams
  stop_words: "english"  # Remove English stopwords
  min_df: 2  # Minimum document frequency for a term
  max_df: 0.9  # Maximum document frequency for a term

# Model Trainer Configuration
model_trainer:
  model_type: "logistic_regression"  # Type of model to train
  solver: "liblinear"  # Solver for Logistic Regression
  penalty: "l2"  # Regularisation type
  random_state: 42  # Random state for reproducibility
  max_iter: 200  # Maximum iterations for convergence
  class_weight: "balanced"  # Handle class imbalance automatically

# Model Evaluation Configuration
model_evaluation:
  metrics:  # Metrics to evaluate the model
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
  validation_split: 0.2  # Percentage of training data to use for validation
  cross_validation: true  # Enable cross-validation
  cv_folds: 5  # Number of folds for cross-validation

# Output Configuration
output:
  model_save_path: "models/trained_model.pkl"  # Path to save the trained model
  vectorizer_save_path: "models/tfidf_vectorizer.pkl"  # Path to save the TF-IDF vectoriser
  evaluation_report_path: "reports/evaluation_report.txt"  # Path to save the evaluation report
  log_file_path: "logs/pipeline.log"  # Path to save the pipeline logs
